Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$outDir = Split-Path -Parent $PSCommandPath

function Escape-PdfText {
    param([string]$Text)

    return ($Text -replace '\\', '\\' -replace '\(', '\(' -replace '\)', '\)')
}

function New-SimpleTextPdf {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Title,
        [Parameter(Mandatory)][string[]]$Lines
    )

    $objects = [System.Collections.Generic.List[string]]::new()
    $objects.Add("<< /Type /Catalog /Pages 2 0 R >>")
    $objects.Add("<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    $objects.Add("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>")
    $objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    $objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")

    $streamLines = [System.Collections.Generic.List[string]]::new()
    $streamLines.Add("BT")
    $streamLines.Add("/F2 16 Tf")
    $streamLines.Add("72 736 Td")
    $streamLines.Add("($(Escape-PdfText $Title)) Tj")
    $streamLines.Add("/F1 10 Tf")
    $streamLines.Add("0 -22 Td")

    foreach ($line in $Lines) {
        if ([string]::IsNullOrWhiteSpace($line)) {
            $streamLines.Add("0 -14 Td")
            continue
        }

        $remaining = $line.TrimEnd()
        do {
            $chunkLength = [Math]::Min(92, $remaining.Length)
            $chunk = $remaining.Substring(0, $chunkLength)
            $streamLines.Add("($(Escape-PdfText $chunk)) Tj")
            $streamLines.Add("0 -14 Td")
            $remaining = $remaining.Substring($chunkLength)
        } while ($remaining.Length -gt 0)
    }

    $streamLines.Add("ET")
    $stream = ($streamLines -join "`n")
    $streamBytes = [System.Text.Encoding]::ASCII.GetBytes($stream)
    $objects.Add("<< /Length $($streamBytes.Length) >>`nstream`n$stream`nendstream")

    $pdf = [System.Text.StringBuilder]::new()
    [void]$pdf.Append("%PDF-1.4`n%Training sample generated by Codex`n")
    $offsets = [System.Collections.Generic.List[int]]::new()
    $offsets.Add(0)

    for ($i = 0; $i -lt $objects.Count; $i++) {
        $offsets.Add([System.Text.Encoding]::ASCII.GetByteCount($pdf.ToString()))
        [void]$pdf.Append("$($i + 1) 0 obj`n")
        [void]$pdf.Append($objects[$i])
        [void]$pdf.Append("`nendobj`n")
    }

    $xrefOffset = [System.Text.Encoding]::ASCII.GetByteCount($pdf.ToString())
    [void]$pdf.Append("xref`n")
    [void]$pdf.Append("0 $($objects.Count + 1)`n")
    [void]$pdf.Append("0000000000 65535 f `n")

    for ($i = 1; $i -lt $offsets.Count; $i++) {
        [void]$pdf.Append(("{0:D10} 00000 n `n" -f $offsets[$i]))
    }

    [void]$pdf.Append("trailer`n")
    [void]$pdf.Append("<< /Size $($objects.Count + 1) /Root 1 0 R >>`n")
    [void]$pdf.Append("startxref`n")
    [void]$pdf.Append("$xrefOffset`n")
    [void]$pdf.Append("%%EOF`n")

    [System.IO.File]::WriteAllText($Path, $pdf.ToString(), [System.Text.Encoding]::ASCII)
}

function Add-AsciiBytes {
    param(
        [Parameter(Mandatory)][System.IO.MemoryStream]$Stream,
        [Parameter(Mandatory)][string]$Text
    )

    $bytes = [System.Text.Encoding]::ASCII.GetBytes($Text)
    $Stream.Write($bytes, 0, $bytes.Length)
}

function New-ImageOnlyPdf {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Title,
        [Parameter(Mandatory)][string[]]$Lines
    )

    Add-Type -AssemblyName System.Drawing

    $width = 1700
    $height = 2200
    $bitmap = [System.Drawing.Bitmap]::new($width, $height)
    $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
    $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $graphics.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit

    $background = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(248, 247, 242))
    $ink = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(38, 38, 38))
    $muted = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(95, 95, 95))
    $pen = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(190, 188, 181), 3)
    $stampPen = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(170, 45, 45), 5)
    $titleFont = [System.Drawing.Font]::new("Arial", 42, [System.Drawing.FontStyle]::Bold)
    $bodyFont = [System.Drawing.Font]::new("Arial", 27, [System.Drawing.FontStyle]::Regular)
    $smallFont = [System.Drawing.Font]::new("Arial", 20, [System.Drawing.FontStyle]::Italic)
    $stampFont = [System.Drawing.Font]::new("Arial", 30, [System.Drawing.FontStyle]::Bold)

    try {
        $graphics.FillRectangle($background, 0, 0, $width, $height)
        $graphics.DrawRectangle($pen, 70, 70, $width - 140, $height - 140)
        $graphics.DrawString($Title, $titleFont, $ink, 115, 130)
        $graphics.DrawString("FICTIONAL TRAINING DOCUMENT - IMAGE-ONLY SCAN", $smallFont, $muted, 115, 205)
        $graphics.DrawLine($pen, 115, 265, $width - 115, 265)

        $y = 320
        foreach ($line in $Lines) {
            if ([string]::IsNullOrWhiteSpace($line)) {
                $y += 38
                continue
            }

            $remaining = $line.TrimEnd()
            do {
                $chunkLength = [Math]::Min(82, $remaining.Length)
                $chunk = $remaining.Substring(0, $chunkLength)
                $graphics.DrawString($chunk, $bodyFont, $ink, 120, $y)
                $y += 48
                $remaining = $remaining.Substring($chunkLength)
            } while ($remaining.Length -gt 0)
        }

        $graphics.TranslateTransform(1220, 1850)
        $graphics.RotateTransform(-12)
        $graphics.DrawRectangle($stampPen, 0, 0, 330, 90)
        $graphics.DrawString("TRAINING COPY", $stampFont, [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(170, 45, 45)), 22, 24)
        $graphics.ResetTransform()

        $imageStream = [System.IO.MemoryStream]::new()
        $bitmap.Save($imageStream, [System.Drawing.Imaging.ImageFormat]::Jpeg)
        $jpegBytes = $imageStream.ToArray()
    } finally {
        $graphics.Dispose()
        $bitmap.Dispose()
        $background.Dispose()
        $ink.Dispose()
        $muted.Dispose()
        $pen.Dispose()
        $stampPen.Dispose()
        $titleFont.Dispose()
        $bodyFont.Dispose()
        $smallFont.Dispose()
        $stampFont.Dispose()
    }

    $pdf = [System.IO.MemoryStream]::new()
    $offsets = [System.Collections.Generic.List[int]]::new()
    $offsets.Add(0)

    Add-AsciiBytes -Stream $pdf -Text "%PDF-1.4`n%Image-only training sample generated by Codex`n"

    $objects = @(
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /Im1 4 0 R >> >> /Contents 5 0 R >>",
        "<< /Type /XObject /Subtype /Image /Width $width /Height $height /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length $($jpegBytes.Length) >>",
        "<< /Length 35 >>`nstream`nq`n612 0 0 792 0 0 cm`n/Im1 Do`nQ`nendstream"
    )

    for ($i = 0; $i -lt $objects.Count; $i++) {
        $offsets.Add([int]$pdf.Position)
        Add-AsciiBytes -Stream $pdf -Text "$($i + 1) 0 obj`n"
        Add-AsciiBytes -Stream $pdf -Text $objects[$i]
        if ($i -eq 3) {
            Add-AsciiBytes -Stream $pdf -Text "`nstream`n"
            $pdf.Write($jpegBytes, 0, $jpegBytes.Length)
            Add-AsciiBytes -Stream $pdf -Text "`nendstream"
        }
        Add-AsciiBytes -Stream $pdf -Text "`nendobj`n"
    }

    $xrefOffset = [int]$pdf.Position
    Add-AsciiBytes -Stream $pdf -Text "xref`n0 $($objects.Count + 1)`n0000000000 65535 f `n"

    for ($i = 1; $i -lt $offsets.Count; $i++) {
        Add-AsciiBytes -Stream $pdf -Text ("{0:D10} 00000 n `n" -f $offsets[$i])
    }

    Add-AsciiBytes -Stream $pdf -Text "trailer`n<< /Size $($objects.Count + 1) /Root 1 0 R >>`nstartxref`n$xrefOffset`n%%EOF`n"
    [System.IO.File]::WriteAllBytes($Path, $pdf.ToArray())
}

$documents = @(
    @{
        Mode = "TextPdf"
        File = "01-auto-policy-renewal-riverbend.pdf"
        Title = "Auto Policy Renewal Declaration"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Riverbend Mutual Insurance Company",
            "Policyholder: Elena Marquez",
            "Mailing Address: 418 Cedar Hollow Lane, Fairview, OH 44126",
            "Policy Number: RMI-AU-482917-26",
            "Policy Type: Personal Auto",
            "Coverage Period: 2026-06-01 to 2027-06-01",
            "Covered Vehicle: 2022 Subaru Outback Touring, VIN ending 7KQ2",
            'Bodily Injury Liability: $250,000 each person / $500,000 each accident',
            'Property Damage Liability: $100,000 each accident',
            'Comprehensive Deductible: $500',
            'Collision Deductible: $1,000',
            'Uninsured Motorist: $250,000 each person / $500,000 each accident',
            'Annual Premium: $1,482.36',
            "Agent: Priya Dorsey, Riverbend Agency Group",
            "Notes: Renewal includes accident forgiveness endorsement and roadside assistance."
        )
    },
    @{
        Mode = "TextPdf"
        File = "02-homeowners-policy-harborstone.pdf"
        Title = "Homeowners Insurance Policy Summary"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Harborstone Casualty and Fire",
            "Insured: Marcus Whitaker",
            "Property Address: 902 Willow Gate Drive, Ashton, NC 27513",
            "Policy Number: HCF-HO-730155-26",
            "Policy Form: HO-3 Special Form",
            "Effective Dates: 2026-04-15 to 2027-04-15",
            'Dwelling Coverage A: $412,000',
            'Other Structures Coverage B: $41,200',
            'Personal Property Coverage C: $206,000',
            'Loss of Use Coverage D: $82,400',
            'Personal Liability Coverage E: $500,000',
            'Medical Payments Coverage F: $5,000',
            'All Other Perils Deductible: $1,500',
            "Wind and Hail Deductible: 2 percent",
            'Annual Premium: $2,318.90',
            "Mortgagee: Northlake Federal Bank, Loan ending 8842"
        )
    },
    @{
        Mode = "ImageScanPdf"
        File = "03-property-claim-first-notice-crescent.pdf"
        Title = "Property Claim First Notice of Loss"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Crescent Valley Assurance",
            "Claimant: Denise Kapoor",
            "Policy Number: CVA-HO-128640-25",
            "Claim Number: CVA-CLM-2026-04192",
            "Date of Loss: 2026-05-03",
            "Reported Date: 2026-05-04",
            "Loss Location: 77 Magnolia Ridge Court, Joliet, IL 60431",
            "Cause of Loss: Kitchen water supply line failure",
            "Reported Damage: Cabinet swelling, hardwood cupping, drywall staining, and baseboard damage.",
            'Initial Reserve: $18,750.00',
            'Deductible: $1,000',
            "Adjuster: Owen Patel",
            "Inspection Scheduled: 2026-05-08 at 10:30 AM",
            "Additional Notes: Insured retained temporary drying vendor before inspection."
        )
    },
    @{
        Mode = "ImageScanPdf"
        File = "04-commercial-liability-claim-summit.pdf"
        Title = "Commercial General Liability Claim Notice"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Summit Prairie Indemnity",
            "Named Insured: Blue Lantern Bakery LLC",
            "Business Address: 1449 Pine Street, Meridian, ID 83642",
            "Policy Number: SPI-CGL-559203-26",
            "Claim Number: SPI-LIAB-26-00918",
            "Loss Date: 2026-03-22",
            "Claimant: Robert Ellison",
            "Allegation: Customer slip and fall near front entry during morning service.",
            "Injury Reported: Sprained wrist and lower back strain.",
            "Witnesses: Jamie Tran, counter associate; Nadine Price, customer.",
            'General Liability Limit: $1,000,000 each occurrence / $2,000,000 aggregate',
            'Medical Expense Limit: $10,000',
            "Assigned Examiner: Leah Morimoto",
            "Current Status: Liability investigation open; surveillance footage requested."
        )
    },
    @{
        Mode = "TextPdf"
        File = "05-workers-comp-claim-northstar.pdf"
        Title = "Workers Compensation Claim Intake"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Northstar Employers Mutual",
            "Employer: Fernway Logistics Inc.",
            "Employee: Thomas Becker",
            "Policy Number: NEM-WC-602884-26",
            "Claim Number: NEM-WC-26-11407",
            "Jurisdiction: Minnesota",
            "Date of Injury: 2026-02-11",
            "Occupation: Warehouse selector",
            "Injury Description: Right shoulder strain while lifting boxed inventory from lower rack.",
            "Medical Provider: Lakeside Occupational Health",
            "Initial Work Status: Modified duty, no lifting over 10 pounds",
            'Average Weekly Wage: $946.20',
            "Claim Representative: Carla Jennings",
            "Notes: Employer provided incident report and supervisor statement."
        )
    },
    @{
        Mode = "TextPdf"
        File = "06-umbrella-policy-briarfield.pdf"
        Title = "Personal Umbrella Policy Declaration"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Briarfield Excess and Specialty",
            "Insureds: Hannah Cho and Miles Cho",
            "Mailing Address: 55 Orchard Meadow Way, Plano, TX 75024",
            "Policy Number: BES-UMB-391044-26",
            "Policy Period: 2026-01-01 to 2027-01-01",
            "Underlying Auto Policy: Raintree Auto RA-208144",
            "Underlying Home Policy: Homestead Shield HS-776201",
            'Personal Umbrella Limit: $2,000,000',
            'Self Insured Retention: $500',
            "Excluded Exposures: Business pursuits, professional services, aircraft ownership.",
            'Annual Premium: $486.00',
            "Producer: Linden Risk Partners",
            "Endorsement: Worldwide personal liability coverage included subject to policy terms."
        )
    },
    @{
        Mode = "ImageScanPdf"
        File = "07-auto-claim-estimate-silvergate.pdf"
        Title = "Auto Physical Damage Estimate Summary"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Silvergate National Insurance",
            "Insured: Arjun Mehta",
            "Policy Number: SNI-AU-814620-25",
            "Claim Number: SNI-APD-26-22260",
            "Date of Loss: 2026-04-09",
            "Vehicle: 2021 Toyota Camry XSE, VIN ending 3LP8",
            "Loss Description: Rear-end collision while stopped at traffic signal.",
            "Primary Damage Area: Rear bumper cover, lift panel, absorber, and left tail lamp.",
            "Labor Hours: Body 12.4, Refinish 6.8, Mechanical 1.1",
            'Parts Total: $2,936.44',
            'Labor Total: $1,742.30',
            'Paint and Materials: $468.75',
            'Deductible: $500',
            'Net Estimate: $4,647.49',
            "Appraiser: Naomi Brooks"
        )
    },
    @{
        Mode = "TextPdf"
        File = "08-life-policy-beneficiary-maple.pdf"
        Title = "Term Life Policy Beneficiary Confirmation"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Maple Crown Life Assurance",
            "Owner and Insured: Lydia Santoro",
            "Policy Number: MCL-TL-247993-24",
            "Product: 20 Year Level Term Life",
            "Issue Date: 2024-09-01",
            'Face Amount: $750,000',
            "Premium Mode: Monthly electronic funds transfer",
            'Monthly Premium: $64.18',
            "Primary Beneficiary: Adrian Santoro, spouse, 100 percent",
            "Contingent Beneficiary: Sofia Santoro, daughter, 50 percent",
            "Contingent Beneficiary: Mateo Santoro, son, 50 percent",
            "Riders: Accelerated death benefit rider included.",
            "Service Note: Beneficiary confirmation requested by policy owner on 2026-05-12."
        )
    },
    @{
        Mode = "ImageScanPdf"
        File = "09-cyber-policy-endorsement-evergreen.pdf"
        Title = "Cyber Liability Endorsement Schedule"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Evergreen Ridge Specialty",
            "Named Insured: Quillstone Dental Group PLLC",
            "Policy Number: ERS-CY-663410-26",
            "Coverage Period: 2026-07-01 to 2027-07-01",
            'Aggregate Limit: $1,000,000',
            'Network Security Liability: $1,000,000',
            'Privacy Liability: $1,000,000',
            'Breach Response Costs: $250,000',
            'Cyber Extortion: $100,000',
            "Business Interruption Waiting Period: 8 hours",
            'Retention: $10,000 each incident',
            "Minimum Security Controls: MFA for remote access, encrypted backups, endpoint protection.",
            "Underwriter: Grant Ivers",
            'Endorsement Note: Social engineering fraud sublimit added at $50,000.'
        )
    },
    @{
        Mode = "ImageScanPdf"
        File = "10-marine-cargo-claim-atlas.pdf"
        Title = "Inland Marine Cargo Claim Report"
        Lines = @(
            "FICTIONAL TRAINING DOCUMENT - NOT A REAL POLICY OR CLAIM.",
            "Carrier: Atlas Bay Marine and Inland",
            "Insured: Redfield Audio Equipment Co.",
            "Policy Number: ABM-IM-510774-26",
            "Claim Number: ABM-CARGO-26-03771",
            "Shipment Reference: RF-ATL-88421",
            "Date of Loss: 2026-01-18",
            "Transit Route: Atlanta, GA to Charlotte, NC",
            "Carrier: Palmetto Freight Services",
            "Commodity: Professional audio mixers and wireless microphone receivers.",
            "Loss Description: Water intrusion discovered on delivery; cartons showed saturation.",
            'Invoice Value: $38,920.00',
            'Salvage Estimate: $6,400.00',
            'Deductible: $2,500',
            "Assigned Adjuster: Bethany Cole",
            "Status: Awaiting carrier response and product repair assessment."
        )
    }
)

foreach ($document in $documents) {
    $path = Join-Path $outDir $document.File
    switch ($document.Mode) {
        "TextPdf" { New-SimpleTextPdf -Path $path -Title $document.Title -Lines $document.Lines }
        "ImageScanPdf" { New-ImageOnlyPdf -Path $path -Title $document.Title -Lines $document.Lines }
        default { throw "Unknown document mode: $($document.Mode)" }
    }
}

"Generated $($documents.Count) mixed PDF training documents in $outDir"
